name: SWE-DOCS-ARTIFACTS

on: 
  push:
    branches:
      - master
      - develop
      - testing-ci

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v1
    
    - name: Search and Compiling Latex Files
      uses: Jatus93/Latex-multicompiler@master
      with:
        path_to_list: .filesToCompile
        artifact: true
    - run: tar -xzf Documents.tar.gz -C Artifacts/
    
    - name: FTP Artifacts Online Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: Artifacts
        ARGS: --transfer-all